name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_BASE: "${{ github.event.repository.name }}"

      - name: Verify build output
        run: ls -l dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./dist

      - name: List uploaded artifacts
        run: 'echo Uploaded artifact: build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: "build"
